import os
print(os.environ['HTTP_ACCEPT'])
print(os.environ['HTTP_HOST'])
print(os.environ['HTTP_USER_AGENT'])
print(os.environ['HTTP_ACCEPT_ENCODING'])
print(os.environ['REMOTE_ADDRESS'])
print(os.environ['REMOTE_PORT'])
print(os.environ['REQUEST_METHOD'])
print(os.environ['REQUEST_URI'])
print(os.environ['SERVER_ADDR'])
print(os.environ['SERVER_PORT'])
print(os.environ['QUERY_STRING'])